### ISSUE TITLE
E2E Club Master app

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/fc-manager-career#2]
Create a first deployed version of the "Manage Club Master" app incl. data model, (draft-enabled) service and Fiori Elements UI.
The app should allow to create and update a club (for now with a name only).
The app should be deployed to a Trial subaccount incl. a HANA database.

### Sub-Tasks

- [x] Create Club data model
- [x] Create Club master service
- [x] Create Manage Club Master app
- [x] Deploy to BTP
