### ISSUE TITLE
E2E Start Career Mode app

### ISSUE THREAD

**Issue by robertwitt** [robertwitt/fc-manager-career#6]
Create an app end-to-end that lets you start a new career mode.

The `ManagerCareer` entity should have following properties:
- Selected club
- Starting season
- League in starting season
- International competition in starting season
- Overall in starting season
- Flag whether this career has started
- Flag whether this career is currently active or not (there can be only one active instance at a time)

Further, DNA and trait points are calculated and displayed read-only.

### Sub-Tasks

- [x] Domain model (incl. code lists)
- [x] Service
- [x] Point calculation logic
- [x] Action to activate career
- [x] Fiori Elements app
- [ ] Deploy to BTP
